# Generated by Django 4.0.3 on 2022-05-14 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=64, unique=True)),
                ('age', models.SmallIntegerField()),
                ('sex', models.TextField(max_length=6)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='myuser', to='snippets.organization')),
            ],
        ),
    ]
